# Generated by Django 4.2.1 on 2023-05-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codigo_e', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('codigo_d', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Apellido', models.CharField(max_length=60)),
                ('Nombre', models.CharField(max_length=60)),
                ('FechaIngreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.curso')),
            ],
        ),
    ]
