# Generated by Django 4.2.1 on 2023-11-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0009_alumno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
