# Generated by Django 4.2.1 on 2023-11-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0010_delete_curso_delete_docente_delete_especialidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='fnacimiento',
            new_name='fecha_nac',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='telefono',
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo',
            field=models.CharField(default='valor_por_defecto', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
    ]
